# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: line_traffic.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'line_traffic.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12line_traffic.proto\x12\x0c\x61map.line.v1\"j\n\x0bTrafficView\x12\x11\n\tline_name\x18\x01 \x01(\t\x12\x14\n\x0ctraffic_time\x18\x02 \x01(\t\x12\x32\n\ndirections\x18\x03 \x03(\x0b\x32\x1e.amap.line.v1.TrafficDirection\"U\n\x10TrafficDirection\x12\x11\n\tdirection\x18\x01 \x01(\x05\x12.\n\x08segments\x18\x02 \x03(\x0b\x32\x1c.amap.line.v1.TrafficSegment\"\xcd\x01\n\x0eTrafficSegment\x12\x0b\n\x03seq\x18\x01 \x01(\x05\x12\x0f\n\x07link_id\x18\x02 \x01(\x03\x12\x12\n\x05state\x18\x03 \x01(\x05H\x00\x88\x01\x01\x12\x12\n\x05speed\x18\x04 \x01(\x05H\x01\x88\x01\x01\x12\x18\n\x0btravel_time\x18\x05 \x01(\x05H\x02\x88\x01\x01\x12\x0f\n\x07reverse\x18\x06 \x01(\x05\x12\x17\n\nline_track\x18\x07 \x01(\tH\x03\x88\x01\x01\x42\x08\n\x06_stateB\x08\n\x06_speedB\x0e\n\x0c_travel_timeB\r\n\x0b_line_track\"j\n\x0bSectionView\x12\x11\n\tline_name\x18\x01 \x01(\t\x12\x14\n\x0ctraffic_time\x18\x02 \x01(\t\x12\x32\n\ndirections\x18\x03 \x03(\x0b\x32\x1e.amap.line.v1.SectionDirection\"N\n\x10SectionDirection\x12\x11\n\tdirection\x18\x01 \x01(\x05\x12\'\n\x08sections\x18\x02 \x03(\x0b\x32\x15.amap.line.v1.Section\"_\n\x07Section\x12\x15\n\rfrom_level_id\x18\x01 \x01(\x05\x12\x13\n\x0bto_level_id\x18\x02 \x01(\x05\x12(\n\x05links\x18\x03 \x03(\x0b\x32\x19.amap.line.v1.SectionLink\"b\n\x0bSectionLink\x12\x0f\n\x07link_id\x18\x01 \x01(\x03\x12\r\n\x05state\x18\x02 \x01(\x05\x12\x0b\n\x03pct\x18\x03 \x01(\x05\x12\x17\n\nline_track\x18\x04 \x01(\tH\x00\x88\x01\x01\x42\r\n\x0b_line_trackb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'line_traffic_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRAFFICVIEW']._serialized_start=36
  _globals['_TRAFFICVIEW']._serialized_end=142
  _globals['_TRAFFICDIRECTION']._serialized_start=144
  _globals['_TRAFFICDIRECTION']._serialized_end=229
  _globals['_TRAFFICSEGMENT']._serialized_start=232
  _globals['_TRAFFICSEGMENT']._serialized_end=437
  _globals['_SECTIONVIEW']._serialized_start=439
  _globals['_SECTIONVIEW']._serialized_end=545
  _globals['_SECTIONDIRECTION']._serialized_start=547
  _globals['_SECTIONDIRECTION']._serialized_end=625
  _globals['_SECTION']._serialized_start=627
  _globals['_SECTION']._serialized_end=722
  _globals['_SECTIONLINK']._serialized_start=724
  _globals['_SECTIONLINK']._serialized_end=822
# @@protoc_insertion_point(module_scope)
